# Introduction to Tensorflow

In [2]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.20.0


In [4]:
# Creating tensor with tf.constant()
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim # SO we see that a scalar is 0-dimensions

0

In [6]:
# Creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim # A vector is 1-dimensions

1

In [ ]:
# Creating a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim # Matrix turns out to be 2 dimensions

2

In [12]:
# Another matrix:
another_matrix = tf.constant([[10.,7.,5.],
                              [3.,2.,5.],
                              [8.,9.,5.]], dtype=tf.float16) # Specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  7.,  5.],
       [ 3.,  2.,  5.],
       [ 8.,  9.,  5.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [ ]:
# Lets create a tensor
tensor = tf.constant([[[1, 2, 3], 
                       [4, 5, 6]],
                      
                      [[7, 8, 9], 
                       [10, 11, 12]],

                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor # So according to the same, we see that we have 3 slices, 2 rows in each slice and 3 columns for each slice.

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim # its a 3-dimension! So Scalars are 0d tensors, vectors are 1d tensors, matrices are 2d tensors.

3

### Creating tensors with `tf.Variables`

In [17]:
# Creating the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
# lets try changing value of changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(1)
unchangeable_tensor # This doesnt work so we cant seem to change constant tensors.

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
# In some cases, during neural network creation, we might want some tensor values to be changed whereas
# for some we wouldn't want our values to be changed. So there is a variable tensor and a constant tensor.
# A lot of the times we dont have to make the decision to to use any, the decision will be made for us behind the scenes
# when tensorflow creates tensors for our neural networks.

In [ ]:
# Let's create Random Tensors.
# Random tensors are tensors of some arbitrary size which contain random numbers. 
# At first, a Neural Network does use random tensors into it, then gradually tunes those to better match its predictions as it learns.

random_1  = tf.random.Generator.from_seed(42) # We used .Generator to be able to use from_seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # Normal distribtuion 
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [29]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [32]:
# Are they equal?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffling the Order of Tensors.

In [37]:
# lets say we are working on a food image classification and have 15 thousand images of ramen and spaghetti.
# the first 10 thousand are ramen and rest 5000 are spaghetti.
# this order could affect how our neural network learns. It might start to adjust the random weights too much so that it matches ramen's.
# SO it might be a good idea to mix up the images or shuffle them, so the neural network can learn both at the same time.
# To it is valuable when you want to shuffle ur data so the inherent order doesnt affect the model.

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [82]:
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=3)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

### Other ways to create tensors

In [ ]:
# just like numpy allows np.ones or zeroes we can do the same with tf and we can also turn numpy arrays to tensors.

In [83]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [84]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays to tensors
>> The Main difference between Numpy arrays and Tensorflow tensors are that tensors can run on a GPU

In [86]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A # now its vector tensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A # Now its a tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [91]:
A = tf.constant(numpy_A, shape=(3, 8))
A 

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
# The values in the shape must be equal to the values in the original array. It was 24 so 3*8=24 and 2*3*4=24

### Getting information from tensors
* shape - the length (no. of elements) of each of the dimensions of a tensor - tensor.shape
* rank - the number of tensor dimensions. Scalar is rank 0, vector is rank 1, etc - tensor.ndim
* axis or dimension - a particular dimension of a tensor - tensor[0], tensor[:,1]..
* size - the total number of items in the tensor - tf.size(tensor)

In [98]:
# Create a rank 4 tensor. (4 dimensions) so shape will have 4 values
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0] # if i write 0 or 1 index, then it will show be output but 3 wont show because fundamentally, the tensor actually contains 2 data 0 index and 1 index, each with 3 other datum

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0, 0] # so 0 index's 0 index's value

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
rank_4_tensor[0, 0, 0]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [108]:
rank_4_tensor.shape, rank_4_tensor.ndim

(TensorShape([2, 3, 4, 5]), 4)

In [111]:
# Get various attributes of a tensor:
print("Data type of every elements: ", rank_4_tensor.dtype)
print("Number of dimensions: ", rank_4_tensor.ndim)
print("Shape of our tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("The total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Data type of every elements:  <dtype: 'float32'>
Number of dimensions:  4
Shape of our tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
The total number of elements in our tensor:  120


In [114]:
# Getting the first element from each dimension from each index except for the final one.
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# rank 2 tensor again
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [116]:
# Get last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [118]:
# Adding an extra dimension to the rank_2_tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [125]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating Tensors (Tensor Operations)

In [ ]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [127]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [128]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [129]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tensor # The original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# We can use tensorflow built in function too. This is fast especially when used with gpu
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplications

In [132]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [133]:
# with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

### Changing datatype of a tensor

In [134]:
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [136]:
B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

### Aggregating Tensors

In [ ]:
D = tf.constant([-1,-2])
tf.abs(D) # abs is for absolute values

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
# Lets try to get the following forms of aggregation as well:
# Max
# Min
# Mean
# Sum

In [140]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([91, 68, 19, 61, 17,  9, 44,  8, 73, 90, 87, 18, 13, 17, 13,  7, 87,
       58, 62, 37, 52, 69, 51, 81, 66, 17, 65, 39, 37, 19, 50, 19, 77, 15,
       96, 13, 85, 13, 94, 71, 86, 43, 91, 17, 37, 27,  4, 63, 67, 81],
      dtype=int32)>

In [141]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [142]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=96>

In [143]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [144]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2424>

### Find the positional maximum and minimum

In [145]:
# Creating a new tensor first for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F) # gives the position of the maximum value of F

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [147]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [148]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

### One-hot encoding tensors

In [ ]:
some_list = [0, 1, 2, 3] # Could be red, green , blue, purple

# one hot encode our list of indices
tf.one_hot(some_list, 4) # 4 is the depth, cuz we have 4 elements.

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Accessing a gpu if available

In [150]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]